export const CREATE_PROFILE = 'CREATE_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';

export const ADD_CONNECTION = 'CREATE_CONNECTION';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';

export const ADD_PROFILE_ROLE = 'ADD_PROFILE_ROLE';
export const REMOVE_PROFILE_ROLE = 'REMOVE_PROFILE_ROLE';

export const ADD_PROFILE_GITHUB = 'ADD_PROFILE_GITHUB';
export const REMOVE_PROFILE_GITHUB = 'REMOVE_PROFILE_GITHUB';

export const ADD_PROFILE_WEBSITE = 'ADD_PROFILE_WEBSITE';
export const REMOVE_PROFILE_WEBSITE = 'REMOVE_PROFILE_WEBSITE';
