export const CHANGE_INPUT = 'CHANGE_INPUT';

export const VALIDATE_URL = 'VALIDATE_URL';
export const VALIDATE_GITHUB = 'VALIDATE_GITHUB';
export const VALIDATE_WEBSITE = 'VALIDATE_WEBSITE';

export const GET_USER_PROFILE = 'GET_PROFILE';
export const GET_PROJECT_OWNER = 'GET_PROJECT_OWNER';

export const GET_PROJECT_FEED = 'GET_PROJECT_FEED';
export const GET_PROJECT_ITEM = 'GET_PROJECT_ITEM';

export const GET_PROFILE_FEED = 'GET_PROFILE_FEED';
export const GET_PROFILE_ITEM = 'GET_PROFILE_ITEM';
